default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: the_laughing_cart_backend_development

test:
  <<: *default
  database: the_laughing_cart_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>